### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by dbpolito** [fireworkweb/inactivejs#1]
### TODOs

- [x] 1. Move `events` to `options` so we can customable: https://github.com/fireworkweb/inactivejs/blob/develop/src/index.js#L20-L23
- [x] 2. Maybe add a throttle to the `_triggerActive` event? To avoid perf problems https://github.com/fireworkweb/inactivejs/blob/develop/src/index.js#L23
- [x] 3. Add `visibility` event
- [x] 4. Option `autostart` and a `start` method
